version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.19.0
    working_directory: ~/jmoney8080.github.com
    steps:
      - checkout
      - run: 
          name: Download dependencies
          command: npm install
      - run: 
          name: Gatsby Build
          command: npm run-script build
      - run: 
          name: Publish github pages
          command: npm run-script gh-pages
workflows:
  version: 2
  build-n-release:
    jobs:
      - build:
          filters:
            branches:
              only: master